---
name: Build

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all pull requests #
#############################
on:
  # Run on every pull request created or updated
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
  pull_request:

###############
# Set the Job #
###############
jobs:
  lint:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3 # tag=v3

      ##########################
      # Github Super Linter needs
      # the latest definitions installed
      ##########################
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3 # tag=v3
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3 # tag=v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3 # tag=v3
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run test