name: Node.js Package

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pocket'
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
      - run: npm install
      - run: npm run build
      - run: npm run test
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry-run: true
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
